version: "3.8"
services:
  server:
    build:
      dockerfile: ./docker/server/Dockerfile
      context: .
    ports:
      - "8888:8888"
    environment:
      - DATABASE_HOSTNAME=database
      - CACHE_HOSTNAME=cache
    depends_on:
      - database
      - cache
  cache:
    image: redis:6.2
    ports:
      - "6379:6379"
  database:
    image: mongo:4.4.5-bionic
    ports:
      - "27017:27017"
    volumes:
      - ./docker/database/data:/data/db
